### ISSUE TITLE
Tech: Azure Machine Learning 

### ISSUE THREAD

**Issue by nhiyobie** [cloudmesh/technologies#9]
Not sure if this is what I am supposed to do, reading the assignment 1 instruction and it looks like I am supposed to assign 10 issues to myself. This is the first one

**Comment by nhiyobie** [comment]
Does not look like I have access to label and assign technology to myself, closing this issue until further instruction...

**Comment by laszewsk** [comment]
TAs will be responsible for coming up with a system for this. They will post soon.

**Comment by nhiyobie** [comment]
@laszewsk thank you professor Laszewski !
